//
//  CreatePasteBinPresenter.swift
//  POD browser
//
//  Created by Warwick McNaughton on 12/01/19.
//  Copyright (c) 2019 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreatePasteBinPresentationLogic {
    func presentSomething(response: CreatePasteBin.Something.Response)
}

class CreatePasteBinPresenter: CreatePasteBinPresentationLogic {
    weak var viewController: CreatePasteBinDisplayLogic?

    // MARK: Do something

    func presentSomething(response: CreatePasteBin.Something.Response) {
        let viewModel = CreatePasteBin.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
