//
//  AuthenticateWithProviderViewController.swift
//  POD browser
//
//  Created by Warwick McNaughton on 9/12/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Provider: Codable {
    var name: String?
}

protocol AuthenticateWithProviderDisplayLogic: class {
    func displayMessage(viewModel: AuthenticateWithProvider.DisplayMessages.ViewModel)
}



class AuthenticateWithProviderViewController: UIViewController, AuthenticateWithProviderDisplayLogic, UITextFieldDelegate, UITextViewDelegate {
    
    // MARK: - Properties
    var interactor: AuthenticateWithProviderBusinessLogic?
    var router: (NSObjectProtocol & AuthenticateWithProviderRoutingLogic & AuthenticateWithProviderDataPassing)?
    var logText = NSMutableAttributedString()
 
    
    @IBOutlet weak var textField: UITextField!
    @IBOutlet weak var textView: UITextView!
    @IBOutlet weak var userInfoButton: UIButton!
    
    // MARK: - Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }


    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: - Setup

    private func setup() {
        let viewController = self
        let interactor = AuthenticateWithProviderInteractor()
        let presenter = AuthenticateWithProviderPresenter()
        let router = AuthenticateWithProviderRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: - Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: - User actions
    
    @IBAction func cancelButtonPressed(_ sender: Any) {
        performSegue(withIdentifier: "UnwindFromAuth", sender: sender)
    }
    
    @IBAction func userInfoButtonPressed(_ sender: Any) {
        fetchUserInfo()
    }
    
    @IBAction func logoutButtonPressed(_ sender: Any) {
        logout()
    }
    
    
    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        textField.delegate = self
//        textField.text = "https://warwicks-macbook.local:8443"
        
        textView.layoutManager.allowsNonContiguousLayout = false
        
        var savedProvider: Provider?
        if let data = UserDefaults.standard.object(forKey: "Provider") as? Data  {
            savedProvider = try? JSONDecoder().decode(Provider.self, from: data)
        }
        if savedProvider != nil {
            textField.text = savedProvider!.name
        }
        
        let notificationCenter = NotificationCenter.default
        notificationCenter.addObserver(self, selector: #selector(handleMessageNotifications(notification: )), name: Notification.Name(rawValue: "MessageNotification"), object: nil)
        
    }

    
    // MARK: - VIP

    /*
     Provider discovery
     Called when user enters provider's url ('issuer')in textfield.
     */
    func fetchConfiguration(issuer: String) {
        let request = AuthenticateWithProvider.FetchConfiguration.Request(issuer: issuer)
        interactor?.fetchProviderConfiguration(request: request, callback: { configuration in
            print(configuration.description())
            self.registerClient(configuration: configuration)
        })
    }
    
    // Dynamic registration
    func registerClient(configuration: ProviderConfiguration) {
        let request = AuthenticateWithProvider.RegisterClient.Request(configuration: configuration) 
        interactor?.registerClient(request: request, callback: { configuration, response in
            //print(configuration!.description())
            print(response!.description())
            self.authenticateWithProvider(configuration: configuration!, clientID: (response?.clientID)!, clientSecret: response?.clientSecret)
        })
    }
    
    // Authentication to provider
    func authenticateWithProvider(configuration: ProviderConfiguration, clientID: String, clientSecret: String?) {
        let request = AuthenticateWithProvider.Authenticate.Request(configuration: configuration, clientID: clientID, clientSecret: clientSecret)
        interactor?.authenticateWithProvider(request: request, viewController: self)
    }

    func logout() {
        interactor!.logout() 
    }
    
    
    // Access user info
    func fetchUserInfo() {
        let request = AuthenticateWithProvider.UserInfo.Request()
        interactor!.fetchUserInfo(request: request)
    }

    
    // Handle messages - send for processing
    func processMessage(message: [String : Any]?) {
        let request = AuthenticateWithProvider.DisplayMessages.Request(message: message)
        interactor!.processMessage(request: request)
    }
    
    
    // Display processed messages on UITextView
    func displayMessage(viewModel: AuthenticateWithProvider.DisplayMessages.ViewModel) {
        if viewModel.status != nil {
           logText.append(viewModel.status!)
        }
        if viewModel.message != nil {
            logText.append(viewModel.message!)
        }
        DispatchQueue.main.async {
            self.textView.attributedText = self.logText
            let bottom = NSMakeRange(self.textView.attributedText.length - 1, 1)
            self.textView.scrollRangeToVisible(bottom)
        }
    }
    
    
    // MARK: - UITextField delegate methods
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        textField.resignFirstResponder()
        if textField.text != nil {
            let provider = Provider(name: textField.text!)
            let encodedProvider = try? JSONEncoder().encode(provider)
            UserDefaults.standard.set(encodedProvider, forKey: "Provider")
        }
        fetchConfiguration(issuer: textField.text!)
        return true
    }
    
    // MARK: - UITextView delegate methods
    
    
    // MARK: - Notifications
    
    @objc func handleMessageNotifications(notification: Notification) {
        let userInfo = notification.userInfo
        processMessage(message: userInfo as? [String : Any])
    }
}
